### ISSUE TITLE
Impossible to destroy a publisher

### ISSUE THREAD

**Issue by showier-drastic** [sequenceplanner/r2r#109]
Hi,

It seems that we cannot destroy a publisher created from the node, because the `destroy` function is private to the inner `Publisher_` type. The only way to remove a publisher is to close the node.

Is it possible to add `Drop` to `Publisher<T>` so we can drop it when necessary?

**Comment by m-dahl** [comment]
Hi,

You are right this functionality is missing. If I remember correctly it is like this is because the node should be the one destroying the publishers so that they can be shared between threads easily. But it seems that there is no function on the node for destroying a publisher either which there ought to be.

**Comment by m-dahl** [comment]
Would the solution in #110 work for you? It does not implement drop but it was the simplest way to add the missing functionality.

**Comment by showier-drastic** [comment]
Thanks for implementing this! Looks good to me.
