### ISSUE TITLE
how to read from a topic whose publisher has `best_effort` qos reliability ?

### ISSUE THREAD

**Issue by midnightexigent** [sequenceplanner/r2r#23]
Hello, this library looks very nice. I would like to use it for a project. 

One of the topics I am trying to read from has a publisher whose qos reliability is set to `best_effort`. Is there currently a way to read those messages regardless ? 

Thanks!

**Comment by m-dahl** [comment]
Hi,

It's currently not possible unfortunately. Since no QoS options have been implemented yet, the subscribers default to `RMW_QOS_POLICY_DURABILITY_SYSTEM_DEFAULT` which I assume is `Reliable`. 

The plan is to add QoS settings at some point but I don't want to commit to a time line, currently I don't have much time to work on the library.

However I think implementing QoS settings is a relatively simple task and would be a good first issue if you want to contribute. See https://github.com/sequenceplanner/r2r/blob/master/r2r_rcl/src/lib.rs#L18 and https://github.com/sequenceplanner/r2r/blob/master/src/subscribers.rs#L170 for starting points.
